# Generated by Django 3.0.2 on 2020-01-21 19:25

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Video')),
            ],
            bases=('main.video',),
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Video')),
            ],
            bases=('main.video',),
        ),
        migrations.CreateModel(
            name='Xvideo',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Video')),
            ],
            bases=('main.video',),
        ),
        migrations.RenameField(
            model_name='video',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='video',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (1, 'HBO'), (2, 'NETFLIX')], max_length=5, null=True),
        ),
    ]
