# Generated by Django 3.0.2 on 2020-01-22 16:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200121_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='hunter',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='video',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (3, 'AMAZONPRIME'), (2, 'NETFLIX')], max_length=5, null=True),
        ),
    ]
