# Generated by Django 3.0.2 on 2020-01-22 17:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200122_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (3, 'AMAZONPRIME')], max_length=5, null=True),
        ),
    ]
