# Generated by Django 3.0.2 on 2020-03-31 17:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200330_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='unlike_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='unlike_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serial',
            name='unlike_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xvideo',
            name='unlike_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (2, 'NETFLIX'), (3, 'AMAZONPRIME'), (4, 'YOUTUBE')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (2, 'NETFLIX'), (3, 'AMAZONPRIME'), (4, 'YOUTUBE')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (2, 'NETFLIX'), (3, 'AMAZONPRIME'), (4, 'YOUTUBE')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (2, 'NETFLIX'), (3, 'AMAZONPRIME'), (4, 'YOUTUBE')], max_length=7, null=True),
        ),
    ]
