# Generated by Django 3.0.2 on 2020-01-23 14:20

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20200122_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='voters',
            field=models.ManyToManyField(related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='votes_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (3, 'AMAZONPRIME'), (2, 'NETFLIX')], max_length=5, null=True),
        ),
    ]
