# Generated by Django 3.0.2 on 2020-04-01 22:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200401_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (1, 'HBO'), (4, 'YOUTUBE'), (2, 'NETFLIX')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (1, 'HBO'), (4, 'YOUTUBE'), (2, 'NETFLIX')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (1, 'HBO'), (4, 'YOUTUBE'), (2, 'NETFLIX')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (1, 'HBO'), (4, 'YOUTUBE'), (2, 'NETFLIX')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
