# Generated by Django 3.0.2 on 2020-04-21 15:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200401_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, default='video-default.jpg', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='video-default.jpg', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serial',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serial',
            name='image',
            field=models.ImageField(blank=True, default='video-default.jpg', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='image',
            field=models.ImageField(blank=True, default='video-default.jpg', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(2, 'NETFLIX'), (1, 'HBO'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
