# Generated by Django 3.0.2 on 2020-05-04 23:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200504_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (5, 'CDA'), (2, 'NETFLIX'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (5, 'CDA'), (2, 'NETFLIX'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (5, 'CDA'), (2, 'NETFLIX'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'HBO'), (5, 'CDA'), (2, 'NETFLIX'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME')], max_length=9, null=True),
        ),
    ]
