# Generated by Django 3.0.2 on 2020-05-06 21:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200504_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.CharField(choices=[('nieznany', 'nieznany'), ('action', 'action'), ('adventure', 'adventure'), ('crime', 'crime'), ('drama', 'drama'), ('historical', 'historical'), ('horror', 'horror'), ('musicals', 'musicals'), ('science fiction', 'science fiction'), ('war', 'war'), ('westerns', 'westerns')], default='nieznany', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('nieznany', 'nieznany'), ('action', 'action'), ('adventure', 'adventure'), ('crime', 'crime'), ('drama', 'drama'), ('historical', 'historical'), ('horror', 'horror'), ('musicals', 'musicals'), ('science fiction', 'science fiction'), ('war', 'war'), ('westerns', 'westerns')], default='nieznany', max_length=20),
        ),
        migrations.AddField(
            model_name='serial',
            name='genre',
            field=models.CharField(choices=[('nieznany', 'nieznany'), ('action', 'action'), ('adventure', 'adventure'), ('crime', 'crime'), ('drama', 'drama'), ('historical', 'historical'), ('horror', 'horror'), ('musicals', 'musicals'), ('science fiction', 'science fiction'), ('war', 'war'), ('westerns', 'westerns')], default='nieznany', max_length=20),
        ),
        migrations.AddField(
            model_name='xvideo',
            name='genre',
            field=models.CharField(choices=[('nieznany', 'nieznany'), ('action', 'action'), ('adventure', 'adventure'), ('crime', 'crime'), ('drama', 'drama'), ('historical', 'historical'), ('horror', 'horror'), ('musicals', 'musicals'), ('science fiction', 'science fiction'), ('war', 'war'), ('westerns', 'westerns')], default='nieznany', max_length=20),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (2, 'NETFLIX'), (5, 'CDA'), (4, 'YOUTUBE'), (1, 'HBO')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (2, 'NETFLIX'), (5, 'CDA'), (4, 'YOUTUBE'), (1, 'HBO')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (2, 'NETFLIX'), (5, 'CDA'), (4, 'YOUTUBE'), (1, 'HBO')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (2, 'NETFLIX'), (5, 'CDA'), (4, 'YOUTUBE'), (1, 'HBO')], max_length=9, null=True),
        ),
    ]
