# Generated by Django 3.0.2 on 2020-05-24 11:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200506_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (1, 'HBO'), (2, 'NETFLIX'), (5, 'CDA')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (1, 'HBO'), (2, 'NETFLIX'), (5, 'CDA')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (1, 'HBO'), (2, 'NETFLIX'), (5, 'CDA')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (1, 'HBO'), (2, 'NETFLIX'), (5, 'CDA')], max_length=9, null=True),
        ),
    ]
