# Generated by Django 3.0.2 on 2020-06-21 22:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200524_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (1, 'HBO'), (2, 'NETFLIX')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (1, 'HBO'), (2, 'NETFLIX')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (1, 'HBO'), (2, 'NETFLIX')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (4, 'YOUTUBE'), (3, 'AMAZONPRIME'), (1, 'HBO'), (2, 'NETFLIX')], max_length=9, null=True),
        ),
    ]
