# Generated by Django 3.0.2 on 2020-08-14 12:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200621_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='xvideo',
            name='genre',
        ),
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (5, 'CDA'), (4, 'YOUTUBE'), (2, 'NETFLIX'), (1, 'HBO')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (5, 'CDA'), (4, 'YOUTUBE'), (2, 'NETFLIX'), (1, 'HBO')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (5, 'CDA'), (4, 'YOUTUBE'), (2, 'NETFLIX'), (1, 'HBO')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='xvideo',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(3, 'AMAZONPRIME'), (5, 'CDA'), (4, 'YOUTUBE'), (2, 'NETFLIX'), (1, 'HBO')], max_length=9, null=True),
        ),
    ]
