# Generated by Django 3.0.2 on 2020-08-14 12:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200814_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (1, 'HBO'), (3, 'AMAZONPRIME'), (2, 'NETFLIX'), (4, 'YOUTUBE')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (1, 'HBO'), (3, 'AMAZONPRIME'), (2, 'NETFLIX'), (4, 'YOUTUBE')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(5, 'CDA'), (1, 'HBO'), (3, 'AMAZONPRIME'), (2, 'NETFLIX'), (4, 'YOUTUBE')], max_length=9, null=True),
        ),
        migrations.DeleteModel(
            name='Xvideo',
        ),
    ]
